name: MineSkyItems
version: '1.0.3-BETA'
main: net.mineskyitems.MineSkyItems
api-version: 26.1

folia-supported: true

depend:
  - MythicMobs
  - MineSkyGameplay
softdepend:
  - MineSkyCustom

authors:
  - "zBrunoC (Bruno C.)"
  - "Drawn (Giovane D.)"

commands:
  item:
    description: Comando principal para o plugin de criação e edição de itens
    aliases:
      - mineskyitems
      - msit