name: MineSkyItems
version: '1.0.1-ALPHA'
main: net.minesky.MineSkyItems
api-version: '1.20'
softdepend:
  - MMOCore
authors: [zBrunoC (Bruno C.), Drawn (Giovane D.)]

commands:
  item:
    Description: Criar ou editar um item
    Usage: /item <editar|criar|give> <nome>
    aliases:
    - msit