name: MineSkyItems
version: '1.0.7-ALPHA'
main: net.mineskyitems.MineSkyItems
api-version: '1.20'
softdepend:
  - MMOCore
authors: [zBrunoC (Bruno C.), Drawn (Giovane D.)]

commands:
  item:
    description: Criar ou editar um item
    usage: /item <editar|criar|give> <nome>
    aliases:
      - msit