name: MineSkyItems
version: '1.0.8-ALPHA'
main: net.mineskyitems.MineSkyItems
api-version: '1.20'
softdepend:
  - MMOCore
authors: [zBrunoC (Bruno C.), Drawn (Giovane D.)]

commands:
  item:
    description: Comando principal para o plugin de criação e edição de itens
    aliases:
      - msit